version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

linters:
  default: all
  enable: []
  disable:
    - dupl # remove
    - nestif # remove
    - noctx
    - errchkjson
    - contextcheck
    - interfacebloat
    - godot
    - gosec
    - cyclop
    - depguard
    - funcorder
    - godox
    - gochecknoglobals
    - err113
    - exhaustive
    - exhaustruct
    - ireturn
    - tagliatelle
    - revive
    - nonamedreturns
    - inamedparam
    - paralleltest
    - maintidx
    - iface
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - goconst
    - gomodguard
  settings:
    funlen:
      lines: 150
      statements: 80
    gocognit:
      min-complexity: 60
    gocritic:
      disabled-checks:
        - captLocal
    staticcheck:
      checks:
        - all
        - "-S1040"
        - "-ST1000"
        - "-ST1003"
        - "-ST1012"
        - "-ST1021"